### ISSUE TITLE
How can I get the finetuned model?

### ISSUE THREAD

**Issue by Carol-gutianle** [yihuaihong/ConceptVectors#1]
Thank you for your inspiring work and open-source codes!
But I have a question that how can I get the finetuned model before unlearning? It seems that there is only scripts for forgetting in this repo.
Thank you for your time.

**Comment by yihuaihong** [comment]
Hi, Tianle.
Thank you very much for your interest in our work!

Actually, we don't have any operations for the vanilla model (LLaMA and OLMo) before unlearning, as our paper describes. We do the unlearning on the vanilla models directly, **trying to erase the knowledge that the models naturally possess after pretraining**. We believe that the knowledge added through finetuning belongs to artificial knowledge (which should be more easier to unlearn), not the knowledge inherently possessed by the model itself.  This is a significant difference between our work and previous unlearning works.

We believe that the topic of LLM Unlearning should be more closely aligned with unlearning the knowledge inherently possessed by the pretrained model itself.


If you have any other questions, or if you encounter any issues while executing the code, please feel free to let me know : )

**Comment by Carol-gutianle** [comment]
Thank you for your clear and in time explanation!
